services:
  mongo:
    image: "memphisos/mongo:4.2"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "27017:27017"
  memphis-cluster:
    image: "memphisos/memphis-broker:latest"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "5555:5555"
      - "6666:6666"
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - CONNECTION_TOKEN=${CONNECTION_TOKEN}
      - DOCKER_ENV=true
      - LOGS_RETENTION_IN_DAYS=3
      - ANALYTICS=true
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET}
    command: >
      -js --auth=memphis     
  ui:
    image: "memphisos/memphis-ui:latest"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "9000:80"
    environment:
      - DOCKER_ENV=true
networks:
  memphis:
    ipam:
      driver: default
